# Generated by Django 5.1.3 on 2024-12-21 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trimestre', max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='score',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='student',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='submitted',
        ),
        migrations.AddField(
            model_name='devoir',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='students.classe'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='devoir',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='trimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.trimestre'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='trimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.trimestre'),
        ),
    ]
