# Generated by Django 5.1.3 on 2024-12-10 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='nni',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
