# Generated by Django 5.1.3 on 2024-11-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_classe_grade_subject_is_active_teacher_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homework',
            new_name='Devoir',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='score',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='student',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='subject',
        ),
        migrations.AddField(
            model_name='composition',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
