# Generated by Django 5.1.3 on 2024-11-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_teacher_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
    ]
