# Generated by Django 5.1.3 on 2024-12-10 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_parent_nni'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='nni',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(default='Composition', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='nni',
            field=models.CharField(default='1234567890', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='nni',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
