# Generated by Django 5.1.3 on 2025-04-30 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_assignment_sessionyear_teacher_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
    ]
