# Generated by Django 5.1.3 on 2024-12-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_trimestre_remove_devoir_due_date_remove_devoir_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='trimestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.trimestre'),
        ),
    ]
