# Generated by Django 5.1.3 on 2024-12-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_devoir_date_alter_devoir_trimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyearmodel',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
