# Generated by Django 5.1.3 on 2024-12-25 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_sessionyearmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_enrolled',
        ),
    ]
