# Generated by Django 5.1.3 on 2024-12-26 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_subject_class_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Exam', to='students.classe'),
        ),
        migrations.AddField(
            model_name='composition',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examsub', to='students.subject'),
            preserve_default=False,
        ),
    ]
