# Generated by Django 5.1.3 on 2025-05-12 15:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='contact_number',
            field=models.CharField(max_length=15, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='school_name',
            field=models.CharField(max_length=255, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classe', verbose_name='Classroom'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(upload_to='assignmentsstudents/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sessionyear',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.sessionyearmodel', verbose_name='Session Year'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload Date'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_enrolled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classe', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='students.grade', verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='monthly_salary_fee',
            field=models.PositiveIntegerField(verbose_name='Monthly Salary Fee'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Exam', to='students.classe', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Coefficient'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='exam_date',
            field=models.DateField(verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(default='Composition', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examsub', to='students.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='trimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.trimestre', verbose_name='Trimester'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='students.classe', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Coefficient'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='name',
            field=models.CharField(default='Devoir', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworkssub', to='students.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='trimestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.trimestre', verbose_name='Trimester'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='students.student', verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='nni',
            field=models.CharField(default='1234567890', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='NNI'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parent_photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_end_year',
            field=models.DateField(verbose_name='Session End Year'),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_start_year',
            field=models.DateField(verbose_name='Session Start Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Enrollment Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='Has Discount'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=40, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nni',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='NNI'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.classe', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Coefficient'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.grade', verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='students.classe', verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='enrollment_date',
            field=models.DateField(verbose_name='Enrollment Date'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nni',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='NNI'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parent_teacher/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly')], default='monthly', max_length=10, verbose_name='Salary Type'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='teachers', through='students.TeacherSubject', to='students.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^[234]\\d{7}$')], verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher', verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='name',
            field=models.CharField(default='Trimestre', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
