# Generated by Django 5.1.3 on 2025-05-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_bio_alter_appconfig_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='has_discount',
            field=models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('50%', '50%'), ('100%', '100%')], default='0%', max_length=10, verbose_name='Discount'),
        ),
    ]
