# Generated by Django 5.1.3 on 2025-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_has_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyearmodel',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Is Current'),
        ),
    ]
