# Generated by Django 5.1.3 on 2025-05-16 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_sessionyearmodel_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='nni',
            field=models.CharField(default='1234567890', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='NNI'),
        ),
    ]
