# Generated by Django 5.1.3 on 2025-05-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_teacher_nni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='subject',
        ),
    ]
