# Generated by Django 5.1.3 on 2025-05-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_composition_classe_remove_composition_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoir',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='subject',
        ),
    ]
