# Generated by Django 5.1.3 on 2025-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_devoir_classe_remove_devoir_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='has_discount',
            field=models.CharField(choices=[('0%', '0%'), ('05%', '05%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('50%', '50%'), ('100%', '100%')], default='0%', max_length=10, verbose_name='Discount'),
        ),
    ]
