# Generated by Django 5.1.3 on 2025-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_has_discount'),
    ]

    
