# Generated by Django 5.1.3 on 2025-05-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_registaion_fees'),
    ]

    
