# Generated by Django 5.1.3 on 2025-05-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_student_registaion_fees_and_more'),
    ]

   
