# Generated by Django 5.1.3 on 2025-05-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_remove_student_registration_fees'),
    ]

    
