# Generated by Django 5.1.3 on 2025-05-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_remove_student_registaion_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=10000, editable=False, max_digits=10, verbose_name='Registration Fee'),
        ),
    ]
