# Generated by Django 5.1.3 on 2025-07-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classe', verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher', verbose_name='Professor'),
        ),
    ]
