services:
  - type: web
    name: monecole
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn school_management.wsgi:application --preload --workers=3"
    staticPublishPath: staticfiles  # Path to your static files directory