# Generated by Django 5.1.3 on 2025-04-28 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_year', models.CharField(max_length=9)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('absence', models.CharField(blank=True, choices=[(None, 'Présent'), ('ABJ', 'Absence Justifiée'), ('ABS', 'Absence Non Justifiée')], max_length=3, null=True, verbose_name='Statut de présence')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notecomposition', to='students.composition')),
                ('sessionyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.sessionyearmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notecompositions', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notecompositions', to='students.subject')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.trimestre')),
            ],
        ),
        migrations.CreateModel(
            name='NoteDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.devoir')),
                ('sessionyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.sessionyearmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.trimestre')),
            ],
        ),
    ]
