# Generated by Django 5.1.3 on 2024-12-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_year', models.CharField(max_length=9)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classe')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notecomposition', to='students.composition')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade')),
                ('sessionyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.sessionyearmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notecompositions', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notecompositions', to='students.subject')),
            ],
        ),
        migrations.CreateModel(
            name='NoteDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classe')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.exam')),
                ('sessionyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.sessionyearmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
        ),
    ]
