# Generated by Django 5.1.3 on 2024-11-27 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('students', '0003_rename_homework_devoir_remove_composition_score_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteStudent',
            new_name='NoteDevoir',
        ),
        migrations.CreateModel(
            name='NoteComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classe')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notecomposition', to='students.composition')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.grade')),
                ('sessionyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.sessionyearmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notecompositions', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notecompositions', to='students.subject')),
            ],
        ),
    ]
