# Generated by Django 5.1.3 on 2024-12-23 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('students', '0004_sessionyearmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notedevoir',
            name='classe',
        ),
        migrations.AddField(
            model_name='notedevoir',
            name='trimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.trimestre'),
            preserve_default=False,
        ),
    ]
