# Generated by Django 5.1.3 on 2024-12-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notedevoir_classe_notedevoir_trimestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notedevoir',
            name='exam',
        ),
    ]
