# Generated by Django 5.1.3 on 2025-05-01 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_question_quiz_answer_question_quiz_result'),
        ('students', '0005_assignment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sessionyear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.sessionyearmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
