# Generated by Django 5.1.3 on 2024-12-25 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_notedevoir_exam'),
        ('students', '0004_sessionyearmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notedevoir',
            name='devoir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.devoir'),
            preserve_default=False,
        ),
    ]
