# Generated by Django 5.1.3 on 2025-05-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_quiz_created_quiz_is_active_quiz_sessionyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
