# Generated by Django 5.1.3 on 2024-12-26 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notedevoir_devoir'),
        ('students', '0006_composition_classe_composition_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notecomposition',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='notecomposition',
            name='grade',
        ),
        migrations.AddField(
            model_name='notecomposition',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='notecomposition',
            name='trimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.trimestre'),
            preserve_default=False,
        ),
    ]
