# Generated by Django 5.1.3 on 2025-05-01 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_quiz_created'),
        ('students', '0005_assignment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.teacher'),
            preserve_default=False,
        ),
    ]
