# Generated by Django 5.1.3 on 2025-05-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_answer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='student',
        ),
    ]
