# Generated by Django 5.1.3 on 2024-11-26 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_classe_grade_subject_is_active_teacher_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportcart_student', to='students.composition')),
                ('sessionyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.sessionyearmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reporting_student', to='students.student')),
            ],
        ),
    ]
