# Generated by Django 5.1.3 on 2024-11-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admins', 'Admins'), ('Adminf', 'Adminf'), ('Professor', 'Professor'), ('Parent/Student', 'Parent/Student')], default='Parent/Student', max_length=20),
        ),
    ]
