# Generated by Django 5.1.3 on 2024-11-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_customuser_nni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='resident_image',
            new_name='image',
        ),
    ]
