# Generated by Django 5.1.3 on 2024-12-18 21:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde initial')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde actuel')),
                ('closed_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Solde de fermeture')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('is_open', models.BooleanField(default=False, verbose_name='Ouvert')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_register', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur en cours')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('utilities', 'Services publics'), ('salary', 'Salaire'), ('supplies', 'Fournitures'), ('other', 'Autre')], default='other', max_length=50, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounting.cashregister', verbose_name='Caisse')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feesstudent', to='students.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frais étudiant',
                'verbose_name_plural': 'Frais étudiants',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('bank', 'Virement bancaire'), ('check', 'Chèque'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Méthode de paiement')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('receipt_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numéro de reçu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.cashregister', verbose_name='Caisse')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_payments', to='students.classe', verbose_name='Classe')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='students.parent', verbose_name='Parent')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='students.student', verbose_name='Étudiant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('due_date', models.DateField(verbose_name='Date limite')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='accounting.cashregister')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionsstudentuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credite'), ('Debit', 'Debite')], default='Credit', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_original', models.BooleanField(default=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.cashregister')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
