# Generated by Django 5.1.3 on 2024-11-29 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentaccount',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='parentaccount',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='parentaccount',
            name='students',
        ),
        migrations.AddField(
            model_name='parentaccount',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_accounts', to='students.classe'),
        ),
        migrations.AddField(
            model_name='parentaccount',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='students.parent'),
        ),
    ]
