# Generated by Django 5.1.3 on 2024-11-29 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_parentaccount_contact_number_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthpayment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthpayment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='monthpayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parentaccount',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='parentaccount',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='parentaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='parent_account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-due_date'], 'verbose_name': 'Frais étudiant', 'verbose_name_plural': 'Frais étudiants'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='months_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='student',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default='description', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Revenu'), ('expense', 'Dépense')], default='income', max_length=10, verbose_name='Type de transaction'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feesstudent', to='students.student'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde initial')),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Solde d'ouverture")),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Solde de fermeture')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde actuel')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('is_open', models.BooleanField(default=False, verbose_name='Caisse ouverte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.cashregister'),
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('due_date', models.DateField(verbose_name='Date limite')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='accounting.cashregister')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionsstudentuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='MonthPayment',
        ),
        migrations.DeleteModel(
            name='ParentAccount',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
