# Generated by Django 5.1.3 on 2024-12-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_fee_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
