# Generated by Django 5.1.3 on 2025-05-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_expense_amount_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('is_fix', models.BooleanField(default=False, verbose_name='FIXED Charge')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='chargetype',
            field=models.ForeignKey( on_delete=django.db.models.deletion.SET_NULL ,blank=True,null=True, related_name='charge', to='accounting.chargetype'),
            preserve_default=False,
        ),
    ]
