# Generated by Django 5.1.3 on 2025-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_chargetype_transaction_chargetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='chargetype',
        ),
        migrations.AddField(
            model_name='chargetype',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
    ]
