# Generated by Django 5.1.3 on 2025-05-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_transaction_chargetype_chargetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='chargetype',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge', to='accounting.chargetype'),
        ),
    ]
