# Generated by Django 5.1.3 on 2024-11-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_transaction_transaction_type_payment_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credite'), ('Debit', 'Debite')], default='Credit', max_length=20),
        ),
    ]
