# Generated by Django 5.1.3 on 2025-05-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_transaction_chargetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
