# Generated by Django 5.1.3 on 2025-05-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_transaction_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Credit', 'Income'), ('Debit', 'Expence')], default='Credit', max_length=20),
        ),
    ]
