# Generated by Django 5.1.3 on 2025-05-18 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_chargetype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='due_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
