# Generated by Django 5.1.3 on 2025-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_studentfee_created_at_studentfee_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
